installedESLint: true

parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module

extends:
  - ./eslint/basics.yml
  - ./eslint/compat.yml
  - ./eslint/filenames.yml
  - ./eslint/import.yml
  - ./eslint/jsx-a11y.yml
  - ./eslint/lodash.yml
  - ./eslint/modern.yml
  - ./eslint/node.yml
  - ./eslint/promise.yml
  - ./eslint/quality.yml
  - ./eslint/react.yml
  - ./eslint/style.yml
