extends:
  - ./eslint/basics.yml
  - ./eslint/compat.yml
  - ./eslint/filenames.yml
  - ./eslint/import.yml
  - ./eslint/jsx-a11y.yml
  - ./eslint/lodash.yml
  - ./eslint/modern.yml
  - ./eslint/node.yml
  - ./eslint/promise.yml
  - ./eslint/quality.yml
  - ./eslint/react.yml
  - ./eslint/readable.yml
  - ./eslint/style.yml

env:
  browser: true
  es6: true
  jest: true
  worker: true
  serviceworker: true

installedESLint: true

parserOptions:
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
    generators: true
    jsx: true
  sourceType: module
