extends:
  - ./eslint/basics.yml
  - ./eslint/compat.yml
  - ./eslint/filenames.yml
  - ./eslint/flowtype.yml
  - ./eslint/import.yml
  - ./eslint/jsx-a11y.yml
  - ./eslint/lodash.yml
  - ./eslint/modern.yml
  - ./eslint/node.yml
  - ./eslint/promise.yml
  - ./eslint/quality.yml
  - ./eslint/react.yml
  - ./eslint/security.yml
  - ./eslint/spacing.yml
  - ./eslint/style.yml
