extends:
  - ./eslint/basics.yml
  - ./eslint/compat.yml
  - ./eslint/cssmodules.yml
  - ./eslint/docs.yml
  - ./eslint/filenames.yml
  - ./eslint/flowtype.yml
  - ./eslint/import.yml
  - ./eslint/jsx-a11y.yml
  - ./eslint/lodash.yml
  - ./eslint/modern.yml
  - ./eslint/node.yml
  - ./eslint/promise.yml
  - ./eslint/quality.yml
  - ./eslint/react.yml
  - ./eslint/spacing.yml
  - ./eslint/style.yml

  # Disabled for now.
  # Waiting for fix for https://github.com/nodesecurity/eslint-plugin-security/issues/16
  # - ./eslint/security.yml
