# Rule Overview
# https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md
#
# Based on Stylelint Config Standard (https://github.com/stylelint/stylelint-config-standard)
# Tweaked for PostCSS usage + CSS Modules support + Lost Grid

rules:
  no-indistinguishable-colors:
    - true
    - severity: warning
