extends:
  - ./stylelint/atrules.yml
  - ./stylelint/basics.yml
  - ./stylelint/block.yml
  - ./stylelint/comments.yml
  - ./stylelint/declaration.yml
  - ./stylelint/functions.yml
  - ./stylelint/mediaquery.yml
  - ./stylelint/rules.yml
  - ./stylelint/selector.yml
  - ./stylelint/types.yml
